version: '3'

services:
  database:
    container_name: psql-dbs
    image: postgres:latest
#    restart: always
    environment:
      POSTGRES_DB : user_handler
      POSTGRES_PASSWORD: pramee-12345
      POSTGRES_USER: postgres
      DATABASE_HOST: psql-dbs


    ports:
      - 5432:5432
    volumes:
      - .././data:/var/lib/postgresql/data

  web:
    container_name: apis
    build: .

    ports:
      - 8081:8081
    restart: on-failure
    environment:
        - WAIT_HOSTS=database:5432
    depends_on:
      - database
    volumes:
      - .././data:/usr/local/app
    command: sh -c "./main"

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

volumes:
  postgres_data:
