version: '3'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: user_handler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pramee-12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

volumes:
  postgres_data:
